@startuml

package 顧客 {

    class 顧客

    class 年齢

    class 性別

    class 証明書

    顧客 "1" *-- "1" 年齢
    顧客 "1" *-- "1" 性別
    顧客 "1" *-- "*" 証明書

    note bottom of 証明書
        メンバーズカード
        学生証
        生徒手帳
        障害者手帳
        エムアイカード
    end note
}

package 映画 {

    class 映画

    class 映画料金種別

    映画 "1" *-- "1" 映画料金種別
}

package 映画館 {

    class 上映スケジュール

    class 上映

    class 上映日

    上映スケジュール "1" *-- "n" 上映
    上映 "1" -- "1" "上映日"
    上映 "1" -left- "1" "映画"
}

package 注文 {

    class 注文条件

    注文条件 "1" --- "1" 顧客
    注文条件 "1" --- "1" 上映
}

package チケット {
    class チケット料金表

    class チケット料金表アイテム

    interface チケット仕様

    class チケット

    class 値段

    チケット料金表 -right-|> 注文条件
    チケット料金表 "1" -- "n" チケット料金表アイテム
    チケット料金表アイテム "1" -- "1" チケット
    チケット料金表アイテム "1" -- "1" チケット仕様
    チケット "1" -- "1" 値段

    note bottom of チケット仕様
        平日仕様
        休日仕様
        レイトショー仕様
        映画の日仕様
        会員仕様
        会員シニア仕様
        etc
    end note
}

@enduml
